
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biz_assist
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123

eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka

# Cloudinary config
cloudinary:
  cloud_name: ddxqozyzn
  api_key: 855135371564347
  api_secret: wTtiULWnPRmlY-6MRWpom6idHl8
  secure: true
